/**
 * JSON stores icon *names*; this maps them to Lucide components.
 * Only icons listed here end up in the bundle.
 */
import {
  AudioLines,
  BadgeCheck,
  Banknote,
  BatteryFull,
  Bluetooth,
  Camera,
  Cpu,
  CreditCard,
  Disc3,
  Droplets,
  Dumbbell,
  Feather,
  Gamepad2,
  Gauge,
  Gift,
  GraduationCap,
  Headphones,
  House,
  Laptop,
  type LucideIcon,
  type LucideProps,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Package,
  Plane,
  Plug,
  RefreshCw,
  RotateCw,
  Ruler,
  ScanFace,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Speaker,
  Usb,
  Volume2,
  Wallet,
  Weight,
  Wifi,
  Zap,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  'audio-lines': AudioLines,
  'badge-check': BadgeCheck,
  banknote: Banknote,
  battery: BatteryFull,
  bluetooth: Bluetooth,
  camera: Camera,
  cpu: Cpu,
  'credit-card': CreditCard,
  disc: Disc3,
  droplets: Droplets,
  dumbbell: Dumbbell,
  feather: Feather,
  gamepad: Gamepad2,
  gauge: Gauge,
  gift: Gift,
  'graduation-cap': GraduationCap,
  headphones: Headphones,
  house: House,
  laptop: Laptop,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  package: Package,
  plane: Plane,
  plug: Plug,
  refresh: RefreshCw,
  rotate: RotateCw,
  ruler: Ruler,
  scan: ScanFace,
  shield: Shield,
  'shield-check': ShieldCheck,
  smartphone: Smartphone,
  speaker: Speaker,
  usb: Usb,
  volume: Volume2,
  wallet: Wallet,
  weight: Weight,
  wifi: Wifi,
  zap: Zap,
}

export function getIcon(name: string): LucideIcon {
  if (import.meta.env.DEV && !ICONS[name]) console.warn(`[icons] unknown icon "${name}"`)
  return ICONS[name] ?? Sparkles
}

export function Icon({ name, ...props }: LucideProps & { name: string }) {
  const Cmp = getIcon(name)
  return <Cmp aria-hidden="true" {...props} />
}
